FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY canary-app.csproj .
RUN dotnet restore canary-app.csproj
COPY . .
RUN dotnet build canary-app.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish canary-app.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "canary-app.dll"]